name: blacksun_2fa
description: "2FA Manager for BlackSun accounts"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  flutter_secure_storage: ^8.1.0
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_dotenv: ^5.1.0
  jwt_decoder: ^2.0.1
  qr_flutter: ^4.1.0
  flutter_animate: ^4.2.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.0.4
  intl: 0.19.0
  local_auth: ^2.1.8
  timer_count_down: ^2.2.2
  clipboard: ^0.1.3
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  animations: ^2.0.7
  permission_handler: ^11.0.0
  device_info_plus: ^9.0.3
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png
  android: true
  web: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
